#ifndef __MyTinkOptions__
#define __MyTinkOptions__

/**
@file
Subclass of TinkOptions, which is generated by wxFormBuilder.
*/

#include "TinkBase.h"

//// end generated include

/** Implementing TinkOptions */
class MyTinkOptions : public TinkOptions
{
	public:
		/** Constructor */
		MyTinkOptions( wxWindow* parent );
	//// end generated class members
	private: 

};

#endif // __MyTinkOptions__
