#ifndef __MyTinkCalculators__
#define __MyTinkCalculators__

/**
@file
Subclass of TinkCalculators, which is generated by wxFormBuilder.
*/

#include "TinkBase.h"

//// end generated include

/** Implementing TinkCalculators */
class MyTinkCalculators : public TinkCalculators
{
	public:
		/** Constructor */
		MyTinkCalculators( wxWindow* parent );
	//// end generated class members

};

#endif // __MyTinkCalculators__
