#ifndef __MyTinkBrewersLog__
#define __MyTinkBrewersLog__

/**
@file
Subclass of TinkBrewersLog, which is generated by wxFormBuilder.
*/

#include "TinkBase.h"

//// end generated include

/** Implementing TinkBrewersLog */
class MyTinkBrewersLog : public TinkBrewersLog
{
	public:
		/** Constructor */
		MyTinkBrewersLog( wxWindow* parent );
	//// end generated class members

};

#endif // __MyTinkBrewersLog__
