#ifndef __TinkMain__
#define __TinkMain__

/**
@file
Subclass of TinkBase, which is generated by wxFormBuilder.
*/

#include "TinkBase.h"

//// end generated include

/** Implementing TinkBase */
class TinkMain : public TinkBase
{
public:
	//// end generated class members

	// custom constructor declared below here
	TinkMain(wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos, const wxSize &size, long style);

	double const APP_VERSION = 0.1;
	int const DEFAULT_ICON_HEIGHT = 16;
	int const DEFAULT_ICON_WIDTH = 16;
};

#endif // __TinkMain__
